// scripts/deploy.ts
// Run after: anchor build && anchor deploy
// Usage: npx ts-node scripts/deploy.ts

import * as anchor from "@coral-xyz/anchor";
import { Connection, PublicKey, Keypair, clusterApiUrl } from "@solana/web3.js";
import { readFileSync } from "fs";
import { homedir } from "os";
import path from "path";

// ── Config ────────────────────────────────────────────────────────────────────

const CLUSTER        = "devnet";
const WALLET_PATH    = path.join(homedir(), ".config/solana/id.json");

function publicKeyFromEnv(name: string, fallback: string): PublicKey {
  const value = process.env[name] ?? fallback;
  try {
    return new PublicKey(value);
  } catch {
    throw new Error(`Invalid ${name} public key: ${value}`);
  }
}

// After `anchor deploy`, copy program IDs here
const BASKET_VAULT_ID = publicKeyFromEnv("BASKET_VAULT_ID", "BCjkqk3PNXuGVnWSpEgWU8m7ewEAQEb4REFPFgxdnHBP");
const SSS_PROGRAM_ID  = publicKeyFromEnv("SSS_PROGRAM_ID", "HJ6TUXQ34XhDrmvcozMsBWhSuEVkEcYeqoTWo1Bcmzet");
const SVS1_PROGRAM_ID = publicKeyFromEnv("SVS1_PROGRAM_ID", "Bv8aVSQ3DJUe3B7TqQZRZgrNvVTh8TjfpwpoeR1ckDMC");

// BASKET mint created by SSS deploy — copy here
const BASKET_MINT     = publicKeyFromEnv("BASKET_MINT", "DmR36BurwkUj9jrN8UpydoNWe3RePZgaeuKgep2XPoXv");

// Asset mints (devnet — create test mints with spl-token create-token)
const ASSET_MINTS = {
  PAXG: publicKeyFromEnv("ASSET_MINT_XAU", "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v"),
  WTI:  publicKeyFromEnv("ASSET_MINT_WTI", "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v"),
  BTC:  publicKeyFromEnv("ASSET_MINT_BTC", "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v"),
  XAG:  publicKeyFromEnv("ASSET_MINT_XAG", "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v"),
  DXY:  publicKeyFromEnv("ASSET_MINT_DXY", "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v"),
  RWA:  publicKeyFromEnv("ASSET_MINT_RWA", "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v"),
};

// Switchboard aggregator stubs (devnet)
const SB_STUB = publicKeyFromEnv("SWITCHBOARD_AGGREGATOR", "HovQMDrbAgAYPCmR4cN8VzQcajF5xqQRBe8EJsF3NPZZ");

// ── Main ──────────────────────────────────────────────────────────────────────

async function main() {
  const conn      = new Connection(clusterApiUrl(CLUSTER), "confirmed");
  const walletKey = JSON.parse(readFileSync(WALLET_PATH, "utf8"));
  const wallet    = Keypair.fromSecretKey(Uint8Array.from(walletKey));

  console.log("Wallet:", wallet.publicKey.toBase58());
  console.log("Balance:", (await conn.getBalance(wallet.publicKey)) / 1e9, "SOL");

  // Load IDL (generated by anchor build)
  const idl = JSON.parse(readFileSync(
    path.join(__dirname, "../target/idl/basket_vault.json"), "utf8"
  ));

  const provider = new anchor.AnchorProvider(conn,
    new anchor.Wallet(wallet), { commitment: "confirmed" }
  );
  anchor.setProvider(provider);

  const idlWithAddress = { ...idl, address: BASKET_VAULT_ID.toBase58() };
  const program = new anchor.Program(idlWithAddress as any, provider);

  // ── Derive PDAs ─────────────────────────────────────────────────────────
  const [globalConfig] = anchor.web3.PublicKey.findProgramAddressSync(
    [Buffer.from("global_config")],
    BASKET_VAULT_ID
  );

  const [vaultAuthority] = anchor.web3.PublicKey.findProgramAddressSync(
    [Buffer.from("basket_vault_authority")],
    BASKET_VAULT_ID
  );

  console.log("GlobalConfig PDA:", globalConfig.toBase58());
  console.log("VaultAuthority PDA:", vaultAuthority.toBase58());

  // ── Build asset registry ─────────────────────────────────────────────────
  // [0]=XAU, [1]=WTI, [2]=BTC (vol proxy), [3]=XAG, [4]=DXY, [5]=RWA
  const SVS_VAULTS = await Promise.all(
    Object.values(ASSET_MINTS).map(async (mintStr, i) => {
      const mint   = mintStr;
      const idBuf  = Buffer.alloc(8);
      idBuf.writeBigUInt64LE(BigInt(0));
      const [vault] = anchor.web3.PublicKey.findProgramAddressSync(
        [Buffer.from("vault"), mint.toBuffer(), idBuf],
        SVS1_PROGRAM_ID
      );
      return vault;
    })
  );

  const PYTH_FEEDS = [
    "765d2ba906dbc32ca17cc11f5310a89e9ee1f6420508c63861f2f8ba4ee34bb2", // XAU
    "a995d00bb36a63cef7fd2c287dc105fc8f3d93779f062f09551b0af3e81ec30b", // WTI
    "e62df6c8b4a85fe1a67db44dc12de5db330f7ac66b72dc658afedf0f4a415b43", // BTC
    "f2fb02c32b055c805e7238d628e5e9dadef274376114eb1f012337cabe93871e", // XAG
    "a39b82aa35a53d7afbef02e1f5c57ebf6b0c1f957a0a35ec1f6e50c7d89d5af5", // DXY
    "a39b82aa35a53d7afbef02e1f5c57ebf6b0c1f957a0a35ec1f6e50c7d89d5af5", // RWA proxy
  ];

  const WEIGHTS_BPS = [2000, 2500, 1500, 1500, 1500, 1000]; // sum = 10_000
  const DECIMALS    = [8, 6, 8, 8, 6, 6];

  const assetRegistry = Object.entries(ASSET_MINTS).slice(0, 3).map(([, mintStr], i) => ({
    mint:                 mintStr,
    svsVault:             SVS_VAULTS[i],
    pythFeedIdHex:        PYTH_FEEDS[i],
    switchboardAggregator: SB_STUB,
    weightBps:            WEIGHTS_BPS[i],
    decimals:             DECIMALS[i],
  }));

  // ── Initialize BasketVault ───────────────────────────────────────────────
  console.log("\nInitializing BasketVault...");

  try {
    const tx = await (program.methods as any)
      .initialize({
        sssProgram:         SSS_PROGRAM_ID,
        svsProgram:       SVS1_PROGRAM_ID,
        rebalanceAuthority: wallet.publicKey,
        emergencyAuthority: wallet.publicKey,
        assetRegistry,
      })
      .accounts({
        deployer:      wallet.publicKey,
        basketMint:    BASKET_MINT,
        globalConfig,
        vaultAuthority,
        tokenProgram:  anchor.utils.token.TOKEN_PROGRAM_ID,
        systemProgram: anchor.web3.SystemProgram.programId,
        rent:          anchor.web3.SYSVAR_RENT_PUBKEY,
      })
      .rpc();

    console.log("✓ BasketVault initialized. TX:", tx);
    console.log("  GlobalConfig:", globalConfig.toBase58());
    console.log("  VaultAuthority:", vaultAuthority.toBase58());

  } catch (e: any) {
    if (e.message?.includes("already in use")) {
      console.log("GlobalConfig already exists — skipping init.");
    } else {
      throw e;
    }
  }

  console.log("\n✓ Deploy complete.");
  console.log("\nNext steps:");
  console.log("  1. npx ts-node scripts/init-vaults.ts  (creates SVS-1 vaults)");
  console.log("  2. Update app/src/utils/constants.ts with deployed addresses");
  console.log("  3. cd app && npm run dev");
}

main().catch(err => {
  console.error("Deploy failed:", err);
  process.exit(1);
});
